Arm: fix cap even checks
Some tests are failing with AArch64 Neon intrinsics
enabled after 83360220dbb92aa04cafefb354546402fcc2ca2a:

ERROR: In function "capWithParity_s16x4_neon" in vvenc/source/Lib/CommonLib/arm/neon/DepQuant_neon.cpp:104: Cap value must be even

This fixes the CHECKD assertion that validates if the cap value is even
which is now implemented the other way around