thirdparty: update bundled SIMDE to simd-everywhere/simde@df69d38
Picks up the fix for a link error on non-glibc platforms (musl, OpenBSD,
MinGW) where GCC 10+ lowers __builtin_roundeven to a roundeven() libm
call that does not exist outside glibc >= 2.25:

  undefined reference to 'roundevenf'

Fixed upstream in simd-everywhere/simde#1398.